version: "2.3"

services:
  realtime:
    image: supabase/realtime:latest
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - SECRET_KEY_BASE=A_SUPER_SECRET_KEY

  db:
    image: postgres:12
    ports:
      - "6543:5432"
    volumes:
      - ./RealtimeTests/db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
