name: Deploy To Azure
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.102

      # dotnet build and publish
      - name: Build with dotnet
        run: dotnet build ./Examples/PresenceExample/PresenceExample.csproj --configuration Release
      - name: dotnet publish
        run: |
          dotnet publish ./Examples/PresenceExample/PresenceExample.csproj -c Release -o ./build
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v1
        with:
          app-name: RealtimeExample
          publish-profile: ${{ secrets.REALTIME_EXAMPLE_PUBLISH_PROFILE }}
          package: ./build
